server:
  port: 8080

cors:
  allowed-origins: http://localhost:3000

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: KOOBS97
    password: ENC(MlggygeeIo9+Sxo2N6ekjZ4FUaWNCtRe)
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      port: 6379
      host: localhost