server:
  port: 8080

cors:
  allowed-origins: http://localhost:5173

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: KOOBS97
    password: ENC(MlggygeeIo9+Sxo2N6ekjZ4FUaWNCtRe)