-- 1. 시퀀스 생성 (의존성 없는 것들 먼저)
CREATE SEQUENCE SEQ_GOURMET_IMAGES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GOURMET_RECORDS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOGIN_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. 독립적인 테이블 생성 (FK 참조가 없는 테이블)

-- 권한 정보
CREATE TABLE ROLE (
                      ROLE_ID VARCHAR2(50) PRIMARY KEY,
                      ROLE_NAME VARCHAR2(100) NOT NULL,
                      DESCRIPTION VARCHAR2(255)
);

-- 메뉴 정보
CREATE TABLE MENU (
                      MENU_ID VARCHAR2(10) PRIMARY KEY,
                      MENU_NAME VARCHAR2(100) NOT NULL,
                      MENU_URL VARCHAR2(255),
                      PARENT_MENU_ID VARCHAR2(10),
                      SORT_ORDER NUMBER(3,0) DEFAULT 0 NOT NULL,
                      IS_VISIBLE VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

-- 보안 질문
CREATE TABLE SECURITY_QUESTION (
                                   QUESTION_CODE VARCHAR2(10) PRIMARY KEY,
                                   QUESTION_TEXT VARCHAR2(300) NOT NULL,
                                   DISPLAY_ORDER NUMBER(3,0) DEFAULT 0,
                                   USE_YN VARCHAR2(1) DEFAULT 'Y' CHECK (USE_YN IN ('Y', 'N')),
                                   CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 다국어 관리 (Identity 사용)
CREATE TABLE MESSAGE_RESOURCE (
                                  ID NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  CODE VARCHAR2(255) NOT NULL,
                                  LOCALE VARCHAR2(10) NOT NULL,
                                  MESSAGE CLOB NOT NULL,
                                  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT UQ_CODE_LOCALE UNIQUE (CODE, LOCALE)
);

-- 사용자 정보
CREATE TABLE USER_INFO (
                           USER_ID VARCHAR2(50) PRIMARY KEY,
                           USER_NAME VARCHAR2(256) NOT NULL,
                           EMAIL VARCHAR2(256) UNIQUE,
                           EMAIL_HASH VARCHAR2(256) UNIQUE,
                           PHONE_NUMBER VARCHAR2(256),
                           BIRTH_DATE VARCHAR2(256),
                           GENDER_CODE VARCHAR2(1) CHECK (GENDER_CODE IN ('M', 'F', 'O')),
                           OAUTH_PROVIDER VARCHAR2(50),
                           OAUTH_PROVIDER_ID VARCHAR2(255),
                           PASSWORD_HASH VARCHAR2(255) NOT NULL,
                           PASSWORD_HINT VARCHAR2(255),
                           PASSWORD_HINT_ANSWER VARCHAR2(255),
                           PASSWORD_UPDATED DATE DEFAULT SYSDATE,
                           ACCOUNT_LOCKED VARCHAR2(1) DEFAULT 'N' CHECK (ACCOUNT_LOCKED IN ('Y', 'N')),
                           REQUIRES_VERIFICATION_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
                           WITHDRAWN VARCHAR2(1) DEFAULT 'N' CHECK (WITHDRAWN IN ('Y', 'N')),
                           LAST_LOGIN_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                           TERMS_AGREE_1 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_1 IN ('Y', 'N')),
                           TERMS_AGREE_2 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_2 IN ('Y', 'N')),
                           TERMS_AGREE_3 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_3 IN ('Y', 'N')),
                           TERMS_AGREE_4 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_4 IN ('Y', 'N')),
                           CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                           UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 휴면 사용자 정보
CREATE TABLE USER_DORMANT_INFO (
                                   USER_ID VARCHAR2(50) PRIMARY KEY,
                                   USER_NAME VARCHAR2(256) NOT NULL,
                                   EMAIL VARCHAR2(256) UNIQUE,
                                   EMAIL_HASH VARCHAR2(256) UNIQUE,
                                   PHONE_NUMBER VARCHAR2(256),
                                   BIRTH_DATE VARCHAR2(256),
                                   GENDER_CODE VARCHAR2(1) CHECK (GENDER_CODE IN ('M', 'F', 'O')),
                                   PASSWORD_HINT VARCHAR2(255),
                                   PASSWORD_HINT_ANSWER VARCHAR2(255),
                                   PASSWORD_UPDATED DATE DEFAULT SYSDATE,
                                   TERMS_AGREE_1 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_1 IN ('Y', 'N')),
                                   TERMS_AGREE_2 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_2 IN ('Y', 'N')),
                                   TERMS_AGREE_3 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_3 IN ('Y', 'N')),
                                   TERMS_AGREE_4 VARCHAR2(1) DEFAULT 'N' CHECK (TERMS_AGREE_4 IN ('Y', 'N')),
                                   CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 3. 관계형 테이블 생성 (FK 포함)

-- 권한/메뉴 매핑
CREATE TABLE ROLE_MENU (
                           ROLE_ID VARCHAR2(50) NOT NULL,
                           MENU_ID VARCHAR2(10) NOT NULL,
                           CONSTRAINT PK_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
                           CONSTRAINT FK_ROLE_MENU_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
                           CONSTRAINT FK_ROLE_MENU_MENU FOREIGN KEY (MENU_ID) REFERENCES MENU (MENU_ID)
);

-- 권한/사용자 매핑
CREATE TABLE ROLE_USER (
                           USER_ID VARCHAR2(50) NOT NULL,
                           ROLE_ID VARCHAR2(50) NOT NULL,
                           CONSTRAINT PK_ROLE_USER PRIMARY KEY (USER_ID, ROLE_ID),
                           CONSTRAINT FK_ROLE_USER_USER FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
                           CONSTRAINT FK_ROLE_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID)
);

-- 맛집 기록
CREATE TABLE GOURMET_RECORDS (
                                 RECORD_ID NUMBER PRIMARY KEY,
                                 USER_ID VARCHAR2(50) NOT NULL,
                                 STORE_NAME VARCHAR2(100) NOT NULL,
                                 CATEGORY VARCHAR2(50) NOT NULL,
                                 VISIT_DATE DATE NOT NULL,
                                 RATING NUMBER(1,0) NOT NULL CHECK (RATING BETWEEN 1 AND 5),
                                 MEMO VARCHAR2(1000),
                                 REFERENCE_URL VARCHAR2(500),
                                 CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                                 UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                                 CONSTRAINT FK_RECORDS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID) ON DELETE CASCADE
);

-- 맛집 이미지
CREATE TABLE GOURMET_IMAGES (
                                IMAGE_ID NUMBER PRIMARY KEY,
                                RECORD_ID NUMBER NOT NULL,
                                IMAGE_ORDER NUMBER NOT NULL,
                                ORIGINAL_FILE_NAME VARCHAR2(255) NOT NULL,
                                STORED_FILE_NAME VARCHAR2(255) NOT NULL, -- STORED_FILE_NAME에서 변경됨 확인 필요
                                IMAGE_URL VARCHAR2(500) NOT NULL,
                                FILE_SIZE NUMBER,
                                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                                CONSTRAINT FK_IMAGES_RECORD_ID FOREIGN KEY (RECORD_ID) REFERENCES GOURMET_RECORDS (RECORD_ID) ON DELETE CASCADE
);

-- 로그인 기록
CREATE TABLE LOGIN_HISTORY (
                               HISTORY_SEQ NUMBER PRIMARY KEY,
                               USER_ID VARCHAR2(100) NOT NULL,
                               LOGIN_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                               IP_ADDRESS VARCHAR2(50),
                               USER_AGENT VARCHAR2(500),
                               COUNTRY_CODE VARCHAR2(10),
                               CITY_NAME VARCHAR2(100),
                               LOGIN_SUCCESS_YN VARCHAR2(1) DEFAULT 'Y'
);

-- 활동 로그 (Identity 사용)
CREATE TABLE USER_ACTIVITY_LOG (
                                   LOG_ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   USER_ID VARCHAR2(50),
                                   ACTIVITY_TYPE VARCHAR2(30) NOT NULL,
                                   ACTIVITY_RESULT VARCHAR2(10) NOT NULL,
                                   REQUEST_IP VARCHAR2(50) NOT NULL,
                                   REQUEST_URI VARCHAR2(255) NOT NULL,
                                   REQUEST_METHOD VARCHAR2(10) NOT NULL,
                                   ERROR_MESSAGE CLOB,
                                   USER_AGENT VARCHAR2(500),
                                   CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 4. 인덱스 추가 (조회 최적화용)
CREATE INDEX IDX_IMAGES_RECORD_ID ON GOURMET_IMAGES (RECORD_ID);
CREATE INDEX IDX_RECORDS_USER_ID ON GOURMET_RECORDS (USER_ID);
CREATE INDEX IDX_LOGIN_HISTORY_USER_ID ON LOGIN_HISTORY (USER_ID);
CREATE INDEX IDX_USER_ACTIVITY_LOG_USER_ID ON USER_ACTIVITY_LOG (USER_ID);
CREATE INDEX IDX_USER_ACTIVITY_LOG_DATE ON USER_ACTIVITY_LOG (CREATED_AT);

-- 5. 트리거 (업데이트 시간 자동 갱신)
CREATE OR REPLACE TRIGGER TRG_MESSAGE_RESOURCE_UPD
    BEFORE UPDATE ON MESSAGE_RESOURCE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- 6. 주석(Comments) 추가
COMMENT ON TABLE GOURMET_IMAGES IS '맛집 기록 이미지 파일 정보';
COMMENT ON TABLE GOURMET_RECORDS IS '맛집 기록 정보';
COMMENT ON TABLE USER_INFO IS '사용자 기본 정보';

COMMIT;